### ISSUE TITLE
Restyle landing

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/www.elgg.org#106]
I have started doing some work on changing the look of the landing and making it "modern" 🚽 
I want to make navbar collapsible, loose community's topbar, and move the items up.

![elgg-org](https://cloud.githubusercontent.com/assets/1202761/18768780/e23749d4-8127-11e6-973e-6ff341ae47ea.png)

**Comment by hypeJunction** [comment]
@Daltonmedia  I can push the changes, you can take over. I have a million other things on the table :)

**Comment by hypeJunction** [comment]
Things we could do:

- [ ] Add a sreenshot to the hero
- [ ] Add a slider of featured items from the showcase
- [ ] Add latest discussions / activity modules

**Comment by Daltonmedia** [comment]
Ok, 
Anyone a problem with losing most of the 'border-radius'ses here?

**Comment by hypeJunction** [comment]
Kill them
