### ISSUE TITLE
Notifications for new discussions lack body

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#20]
I just got an email with the correct subject line but a completely blank body. No link to discussion and no content.

**Comment by jeabakker** [comment]
discussion replies have a body, so only the 'new' is lacking

**Comment by juho-jaakkola** [comment]
For me also the replies are empty.

**Comment by ewinslow** [comment]
This is a really poor and unprofessional experience. We need to fix it asap. Probably very simple fix.

**Comment by juho-jaakkola** [comment]
Already fixed in https://github.com/Elgg/Elgg/pull/8836

**Comment by ewinslow** [comment]
I don't understand how that fixes the issue?

**Comment by juho-jaakkola** [comment]
Wrong amount of arguments caused the translation to fail.

**Comment by juho-jaakkola** [comment]
At least that fixed it in my test site.

**Comment by ewinslow** [comment]
Ah ok. I see now. Too bad it's so brittle...
