### ISSUE TITLE
community site: redirect to https://elgg.org/ after making a posting is annoying

### ISSUE THREAD

**Issue by iionly** [Elgg/www.elgg.org#37]
I don't think it was the same before the site was upgraded to 2.0. I would say you rather ended on the referer page after making a posting instead.

**Comment by ewinslow** [comment]
What kind of posting were you making? plugin comment, discussion reply, new discussion?

**Comment by iionly** [comment]
It happened on making a discussion reply. I haven't started a new discussion or make a comment since the upgrade so I can't say if it might happen then, too.

The redirect also happens when logging in though.

**Comment by ewinslow** [comment]
I have not experienced this. Are.you able to consistently repro?

**Comment by iionly** [comment]
It seems it's connected with using the RefControl addon in Firefox that suppresses the referer. With the addon disabled I stay on the current page after an action (not only making a posting but for example also deleting the posting again). With the addon enabled I get redirected to the elgg.org index page all the time. This behaviour did not occur with Elgg 1.X where I stayed on the current page even with the referer suppressed by the RefControl addon, so it might be something different in Elgg 2.X with the forwarding.

**Comment by iionly** [comment]
Had no time to check the settings of the RefControl addon this morning. I had added an exception for community.elgg.org. That's why I stayed on the current page after an action. So I have just have to add a new exception for elgg.org now to avoid the redirect to the index page.

Meaning: nothing changed on the community site. Not an issue.

**Comment by ewinslow** [comment]
Thanks for looking into that!
