### ISSUE TITLE
Forward to /community if coming from community.elgg.org/

### ISSUE THREAD

**Issue by brettp** [Elgg/www.elgg.org#42]
community.elgg.org should forward to elgg.org/community. It's confusing if you go to community.elgg.org and end up on elgg.org's home page.

**Comment by ewinslow** [comment]
How about elgg.org/activity?

**Comment by ewinslow** [comment]
elgg.org/community gives a "Page not found" error

**Comment by ewinslow** [comment]
Forwarding to /activity now, from both http and https.

**Comment by brettp** [comment]
Yes, I meant /activity.
