### ISSUE TITLE
Deprecate elgg_view_menu_item()

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/www.elgg.org#51]
Unsure why, but ```navigation/menu/elements/item``` calls ```elgg_view_menu_item()```. I propose we deprecate and move all the view rendering logic to the view instead.

**Comment by ewinslow** [comment]
Why?

**Comment by hypeJunction** [comment]
Seems strange that you call ```elgg_view_menu_item()``` from an item view. Either we should move all logic into that function, or out of it.

**Comment by hypeJunction** [comment]
I meant to open this in Elgg/Elgg.
