### ISSUE TITLE
Marking a discussion off-topic fails to create the new topic

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#52]
I clicked "off topic", typed a new title, and submitted the form.

Expected result is that the new discussion would be created and I'd be perhaps forwarded there or kept on the same page I was already on.

I got forwarded to the elgg.org homepage instead. The topic seems not to have been created.

The original off-topic comment *was* correctly modified to be marked as off-topic.

**Comment by juho-jaakkola** [comment]
Closing because I cannot reproduce the problem.
