### ISSUE TITLE
Off-topic comment should be deleted entirely after moving to new discussion

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#54]
We leave the comment content behind currently. I think this makes the "it was moved" part much less visible. It's also safer since we don't have revision control on comments at this point...

**Comment by juho-jaakkola** [comment]
PR: https://github.com/Elgg/community_groups/pull/37

**Comment by juho-jaakkola** [comment]
Fixed in the community_groups repo.
