### ISSUE TITLE
Make search more prominent

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#64]
Right now it's tucked away in the sidebar. We have solr running. It's fast, not something to be afraid of users using! It'd be great to have it more front-and-center. Maybe that would encourage folks to look for existing answers instead of posting duplicate questions?

**Comment by ewinslow** [comment]
Also, it is often the only thing in the sidebar, which either:
 * on desktop: wastes horizontal space, leaving a gaping unused white area underneath it, or
 * on mobile: gets moved to the very bottom of the page, hiding it from users even further

**Comment by mrclay** [comment]
Moved to https://github.com/Elgg/Elgg/issues/10271
