### ISSUE TITLE
Relative times look goofy

### ISSUE THREAD

**Issue by ewinslow** [Elgg/www.elgg.org#66]
"a few seconds ago", "a few minutes ago", etc. This format has repeatedly felt annoying to me especially when the times are far back (1230 days ago? How is that helpful at all?). I don't know if I can give any objective evaluation of it, but it just seems goofy to me. I suspect perhaps that people don't think of past events in terms of "how many days ago" they happened. They think of them in terms of fixed dates that don't change. E.g. If I asked what you were doing "5084 days ago", that probably doesn't mean much to you, but if I asked what you were doing "Tuesday, September 11, 2001," that date might hold some more obvious significance (i.e. WTC terrorist attack).

I vote we use absolute times that just leave off unnecessary details as appropriate:
* Today at 5:30pm (any same-day activity)
* Yesterday at 5:30pm (any yesterday activity)
* Tuesday at 5:30pm (before yesterday, same week)
* Tuesday, September 11 (different week, same year) 
* Tuesday, September 11, 2001 (different year)

Future times are easy enough to cover, we just add:
* Tomorrow at 5:30pm (any activity happening on the next calendar day)

Hovering over the date could, as it does now, give you the fully specified time: "5:30pm Friday, August 14, 2015 PDT"

Would like to try this out on elgg.org and see if it improves the experience at all...

**Comment by beck24** [comment]
Why not just a standard date format?

**Comment by ewinslow** [comment]
There are a lot of those :)

**Comment by ewinslow** [comment]
I think that picking a standard date format would be a good baseline,
though. We can simplify from there if it's valuable, or we can just leave
it at is.

Have any favorite standard formats?

On Sunday, September 20, 2015, Matt Beckett <notifications@github.com>
wrote:

> Why not just a standard date format?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elgg/www.elgg.org/issues/66#issuecomment-141875248>.
>


-- 
Evan Winslow
http://community.elgg.org/profile/ewinslow

**Comment by mrclay** [comment]
Moved to https://github.com/Elgg/Elgg/issues/10272
