### ISSUE TITLE
You must to post replies.

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/www.elgg.org#82]
I see this on a discussion page in a group I am not a member of. Not sure if it's a core issue or something on elgg.org

**Comment by hypeJunction** [comment]
![youmust](https://cloud.githubusercontent.com/assets/1202761/9909537/fc6ea1a8-5c98-11e5-9c0f-c489701cf947.png)

**Comment by iionly** [comment]
Just wanted to report the same. In views/default/discussion/replies.php there's the line
```php
echo "You must $join_group to post replies.";
```
where $join_group is assigned the missing part using the deprecated output/confirmlink view.

Wouldn't it be better to make the whole message a language key anyway beside fixing the deprecation issue. Maybe other text output too?

**Comment by ewinslow** [comment]
`$join_group` is meant to be a link, I assume, and I'm guessing we generally frown upon putting links into translatable text, since the URL is dynamic.

Seems to be the standard approach to addressing this is splitting up the explanation and the call to action:

```
<span>You must join this group to post replies.</span>
<a href=...>Join</a>
```

That way there are no links in the middle of sentences.

**Comment by iionly** [comment]
The code in views/default/discussion/replies.php is
```php
		$join_group = elgg_view('output/confirmlink', array(
			'href' => '/action/groups/join?group_guid=' . $group->getGUID(),
			'text' => 'join this group',
			'confirm' => 'Join this group?'
		));
		echo "<div class=\"elgg-box elgg-state-notice\">";
			echo "You must $join_group to post replies.";
		echo "</div>";
```
So the problem isn't that $join_group is a link (apart from using the deprecated output/confirmlink view) but that the link text and the rest of the text output is hardcoded.

**Comment by iionly** [comment]
Would it work like that or would it be necessary to include the html markup in the language string?
